### PR TITLE
Code simplification

### PR DESCRIPTION
**Pull request by dubrovkinmaxim**
Using auto properties to simplify code.
Data transfer objects were extracted to separated files.

### CODE REVIEW

**Comment by dubrovkinmaxim** [comment]
I will sign CLA soon:)

**Comment by thinkingserious** [comment]
@dubrovkinmaxim,

Any update on the CLA? Is there anything I can do to help?

**Comment by dubrovkinmaxim** [comment]
@thinkingserious Sorry I was on vacation. I will sign it tomorrow.

**Comment by thinkingserious** [comment]
Awesome, thanks!

**Comment by dubrovkinmaxim** [comment]
I going to rebase,resolve conflicts and update PR

**Comment by thinkingserious** [comment]
Thanks @dubrovkinmaxim!

**Comment by thinkingserious** [comment]
Hi @dubrovkinmaxim,

This ticket finally came up to the top of my list. Could you please fix the conflicts so I can test and marge? Thanks!

**Comment by thinkingserious** [comment]
Thanks!

**Comment by dubrovkinmaxim** [comment]
@thinkingserious you are welcome :)

**Pull request merged**
