### PR TITLE
Added .ConfigureAwait(false) where async continuations exist.

### LINKED ISSUE #198: Missing ConfigureAwait(false) on async calls
I there, I'm looking at migrating to SendGrid and was browsing through the C# support. I noticed you are using async/await (great!) but that the calls did not use .ConfigureAwait(false). This is going to cause unnecessary thread context synchronization. Can you please add ConfigureAwait calls into all the await executions.

### PR DESCRIPTION
**Pull request by roryprimrose**
Added .ConfigureAwait(false) where async continuations exist.

Removed async/await keywords where there is no continuation (avoids perf hit of the state machine being generated by the compiler).

Closes #198

### CODE REVIEW

**Comment by roryprimrose** [comment]
Build failure is presumably because the build machine lacks the SendGrid API Key in the environment variable???

**Comment by dubrovkinmaxim** [comment]
Yes! I think it would be fixed soon =)

**Comment by thinkingserious** [comment]
Yes, I think there is an issue with our API Key on Travis and I'm hoping to get that fixed soon.

**Comment by thinkingserious** [comment]
Hello @roryprimrose,

In the new version of this library, the Environment dependency is removed.

This issue would now be located here: https://github.com/sendgrid/csharp-http-client, which is the HTTP client this library now depends upon. I believe your pull request will belong there.

The new version of this library is located here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

If you decide to re-submit this pull request, we will need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla

Thank you for your support!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Please do take us up on our offer for swag @roryprimrose. Just email us at dx@sendgrid.com with your T-shirt size. We GREATLY appreciate your support!

**Pull request closed without merging**
