### PR TITLE
Add a StringToEmailAddress helper function

### PR DESCRIPTION
**Pull request by JefStat**

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome @JefStat!

Do you mind adding a test or two [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/tests/SendGrid.Tests/Integration.cs)? Thanks!

**Comment by thinkingserious** [comment]
Would you mind adding your tests to [this file](https://github.com/sendgrid/sendgrid-csharp/blob/master/tests/SendGrid.Tests/Integration.cs) instead. We can then create a new issue to split the tests out into different files.

**Comment by JefStat** [comment]
No clue how you are using travis-ci with Integration.cs so here's a go at just copying in the class

**Comment by thinkingserious** [comment]
Thanks!

**Comment by thinkingserious** [comment]
Hello @JefStat,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
