### PR TITLE
Simplifying, formatting, refactoring

### PR DESCRIPTION
**Pull request by dubrovkinmaxim**
Code cleanup and readability improvement.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thank you for the pull request! We have added it's review to our backlog.

**Comment by dubrovkinmaxim** [comment]
You are welcome. I'm going to fix tests :)

**Comment by dubrovkinmaxim** [comment]
@thinkingserious  I have checked out the latest version of the .travis.yml from master, but tests are still failing =(

**Comment by thinkingserious** [comment]
Hmm, maybe I need to update the secure variables in Travis, since it looks like there is difficulty with authorization. I'll have to take a deeper look using my local setup. Thanks!

**Comment by thinkingserious** [comment]
Hello @dubrovkinmaxim,

I'm closing this pull request because we are launching a new version of this library that is completely refactored. You can check it out here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta/

If you wish to contribute, we will need your pull requests to be against that branch and we need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla

Thank you for your support!

With Best Regards,

Elmer

**Pull request closed without merging**
