### PR TITLE
Improve consistency with System.Net.MailAddress #338

### PR DESCRIPTION
**Pull request by stevensona**
Greetings dudes,

This is my attempt at resolving inconsistencies between how `SendGrid.Helpers.Mail.Email` and `System.Net.MailAddress` handles email address display names, specifically with regards to quotation marks as discussed in #338. My solution is to strip out leading and trailing quotes from the display name. I've added two tests to the test suite to test this behavior.

Something I'd like feedback on is whether or not the unit tests for this should be specifically testing the cases described in #338, because to be honest, I was having a difficult time reproducing all aspects of the bug report ("Invalid email" errors).

Regards,
Adam

### CODE REVIEW

**Comment by thinkingserious** [comment]
@stevensona,

It appears to me that the tests you have added fix the issue.

@snumpy,

Do you mind retesting using this fix?

**Comment by thinkingserious** [comment]
LGTM @stevensona,

Let's give @snumpy a few more days to take look. 

Thanks!

**Comment by snumpy** [comment]
@thinkingserious and @stevensona,

I apologize for the extended delay in responding - I'm new to GitHub and didn't realize I wasn't receiving notifications for activity. I don't have the tools (or time) to compile and check the fix; however, I have looked through the code, and it appears to appropriately address the issue.

Would it be a good idea for the unit test to also ensure Cc and Bcc addresses are properly handled?

Also, when can I expect this fix to make its way into the nuget package?

Thanks to both of you,
Richard

**Comment by thinkingserious** [comment]
Hi @snumpy,

Thanks for checking back in!

I think it's a good idea to add the unit tests you describe.

@stevensona, do you still have time for that? If not, I can work on getting the additional tests added.

**Comment by stevensona** [comment]
I cleaned up the tests to remove their dependence on the "Email" class. This demonstrates that the functionality that was changed is constrained to the Email class, and BCC and CC (and just normal To) don't need to be tested at all. Also I squashed my commits.

**Comment by thinkingserious** [comment]
Hi @stevensona,

This one finally bubbled up to the top of my backlog. Could you please resolve the conflicts? Thanks!

**Pull request closed without merging**
