### PR TITLE
How to use template email

### PR DESCRIPTION
**Pull request by ccasbre27**
Added code for show how to use template in the email

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks for contributing to SendGrid Open Source! We think it's awesome when community members contribute to our projects and want to celebrate that.

The following link will ask you to authenticate with Github (so we can verify your identity). You'll then be asked for your shipping address so that we can send you a thanks for contributing.

[Click Here to Continue »](https://sendgrid-contribot.herokuapp.com/)

Once again, thank you!

**Comment by ccasbre27** [comment]
You're welcome! It appears that all the t-shirts are out of stock :S

**Comment by thinkingserious** [comment]
Sorry about that! 

Please email me at myfirstname@sendgrid.com with your mailing address and T-shirt size.

**Comment by ccasbre27** [comment]
ok thanks!

**Pull request merged**
