### PR TITLE
chore: Upgrade from .NET Core 2.1 to .NET Core 3.1 (#1112)

### LINKED ISSUE #1112: .NET Core 2.1 will reach End of Support on August 21, 2021
### Issue Summary

.NET Core 2.1 will reach End of Support on August 21, 2021

- https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/

### PR DESCRIPTION
**Pull request by akunzai**
Fixes #1112 

- Upgrade from .NET Core 2.1 to .NET Core 3.1
- [Migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to) for example projects that running on .NET Core 3.1.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-csharp/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @akunzai!

Thank you for the PR!! 

Reference: https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021 

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

Internal Tracking: DI-1564

**Review by fabio-s-franco — APPROVED** [review]

**Comment by eshanholtz** [comment]
@akunzai 

A quick confirmation: These changes should not break users who choose to use this helper library on .NET Code 2.1, but rather upgrades our examples to use .NET Code 3.1?

**Comment by akunzai** [comment]
@eshanholtz

Yes, 

1. In `SendGrid.csproj`, the `TargetFrameworks` was not modified, it keeps the compatibility with .NET Core 2.1.
2. In `RetryDelegatingHandler.cs` [changes](https://github.com/sendgrid/sendgrid-csharp/pull/1110/commits/99cd73e508a2be79ad371e84fc65a0b67edf1572), the [TaskCanceledException](https://docs.microsoft.com/dotnet/api/system.threading.tasks.taskcanceledexception) was inherited from [OperationCanceledException](https://docs.microsoft.com/dotnet/api/system.operationcanceledexception), it keeps the compatibility too.
3. I upgrade tests to use .NET Core 3.1 too, not just examples.

**Comment by waynebrantley** [comment]
3.1 is no longer supported in dec 2022.  I agree with your work, but perhaps just multi-target netstandard2.0 and net6.0.
And does sendgrid/twilio have any intent on merging this?

**Comment by akunzai** [comment]
Hi @waynebrantley, thanks for your recognition, perhaps your can open another PR to remove outdated TFMs(netstandard1.3;net452;net40).

Please give this PR more thumbs up to make sendgrid/twilio raise priority of this PR.

**Comment by waynebrantley** [comment]
I would but only if we knew they were willing to merge it!  
@mortenbock @rakatyal any thoughts?

**Comment by rakatyal** [comment]
Hi @waynebrantley and @akunzai! We definitely appreciate your contributions and will work on merging the changes on our end. I will appreciate if you can tag me once this is ready so that it doesn't get lost in my email. Thank you!

**Comment by akunzai** [comment]
Hi @rakatyal @eshanholtz @thinkingserious,

It is ready to merge for a long while. Please consider merge it before .NET Core 3.1 goes EOL, thanks.

**Comment by rakatyal** [comment]
Hi! Based on internal discussions, we won't be considering these changes since we will look to upgrade to .Net 6 taking into account the .Net Core EOL. Apologies for the confusion.

**Comment by akunzai** [comment]
Hi @rakatyal, 

It's OK! never mind, I's going to close this PR, thanks for your confirmation!

**Comment by Sharparam** [comment]
@rakatyal Seeing how the issues page has been disabled(?) I'll ask here: How are we supposed to report bugs/feature requests on this library now? The links in the README for "feature request" and "bug report" now point to a non-existing header in the CONTRIBUTING document.

**Comment by rakatyal** [comment]
Hi @Sharparam, you can report bugs/feature requests to us through [Twilio SendGrid Support Help Center](https://support.sendgrid.com/).

**Pull request closed without merging**
