### PR TITLE
Update Create Template Version Docs as per sendgrid support request

### LINKED ISSUE #668: Creating Transactional Templates results in a bad request malformed json
#### Issue Summary

Creating a transactional template version with the following code results in a malformed json error

``` c#
string data = @"{
  'active': 1, 
  'html_content': '<%body%> <p> Test </p>' , 
  'name': 'example_version_name', 
  'plain_content': '<%body%> Test', 
  'subject': '<%subject%> Test Subject', 
  'template_id': 'guid'
}";
var json = JsonConvert.DeserializeObject<Object>(data);
data = json.ToString();
var template_id = "guid";
var response = await client.RequestAsync(method: SendGridClient.Method.POST, urlPath: "templates/" + template_id + "/versions", requestBody: data);
Console.WriteLine(response.StatusCode);
Console.WriteLine(response.Body.ReadAsStringAsync().Result);
Console.WriteLine(response.Headers.ToString());
Console.ReadLine();
```

#### Steps to Reproduce

1. Perform this Request
2. Malformed json response is returned

Expected template version to be successfully created

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Platform ASP.NET
* .NET Version: 4.6.2

### PR DESCRIPTION
**Pull request by 06needhamt**
Update Create Template Version Docs as per sendgrid support request 'https://support.sendgrid.com/hc/en-us/requests/1382463?flash_digest=6a468b8f19e66f1d040d6363d45d233430c64c03'

Fixes #668

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=669) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=669) it.</sub>

**Comment by 06needhamt** [comment]
@thinkingserious Any ETA as to when this will be merged?

**Comment by thinkingserious** [comment]
Hello @06needhamt,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
No problem, thanks @06needhamt!

**Pull request merged**
