### PR TITLE
Fixed code samples

### PR DESCRIPTION
**Pull request by MaximRouiller**
Code sample had a `ver` instead of `var`. Fixed.

### CODE REVIEW

**Comment by MaximRouiller** [comment]
This is a change to the documentation. Not the code itself. The failure of Travis-ci should be ignored in this scenario.

**Comment by MaximRouiller** [comment]
Guys? 2 weeks for a merge?

This is just documentation.

**Comment by thinkingserious** [comment]
Thank you @MaximRouiller!

We've gotten behind in our pull/issue request reviews in preparation for our new library release, which you can check out here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

**Comment by MaximRouiller** [comment]
awesome :)

**Pull request merged**
