### PR TITLE
Update USE_CASES.md

### PR DESCRIPTION
**Pull request by Niladri24dutta**
This pull request is to merge the changes in master related to the sample code provided in the use case for "**Send a Single Email to Multiple Recipients**" and "**Send Multiple Emails to Multiple Recipients**" . The missing line of code `var response = await client.SendEmailAsync(msg);` was added to send email for these two cases.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=496) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=496) before we can accept your contribution.<br/><hr/>**Niladri28dutta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=496) it.</sub>

**Comment by Niladri24dutta** [comment]
@thinkingserious  Hi please review and approve the PR if it looks fine. Let me know if anything else is required from my end.

**Comment by thinkingserious** [comment]
Hello @Niladri24dutta,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Niladri24dutta** [comment]
Ok sure will do but as I am from outside US will it be any issue?

**Comment by thinkingserious** [comment]
No issue @Niladri24dutta. Thanks!

**Comment by Niladri24dutta** [comment]
@thinkingserious  Hi There can you please let me know how long does it take usually to receive the T Shirt as my current location is India. I Haven't received it yet and not sure how to check the status. Thanks

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

I'm not quite sure. We send the request out on 7/20. I have sent an email to our provider to find out more.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

I have discovered that we ran out of shirts and they should be replenished within 1-2 more weeks.
 
From there, it will take about 5-7 days to arrive in India. You will probably get a call from Customs to authorize the clearance when it lands in country.

My apologies for the delay.

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
@thinkingserious ok , is there anything required from my end regarding the authorization for clearance with customs? Do I have to provide any documents?

**Comment by thinkingserious** [comment]
I don't think so, @Niladri24dutta.

**Comment by Niladri24dutta** [comment]
@thinkingserious Just checking again as I have not received the T shirt till now, can you please let me know whether the same has been dispatched yet?

**Comment by thinkingserious** [comment]
I have sent an email to follow up with our swag provider to find out if our inventory has been replenished. Once they respond, I'll update you here. Thanks!

**Comment by thinkingserious** [comment]
@Niladri24dutta,

The shirts will be in by late next week. Once they arrive, they will be shipped. Thanks!

**Comment by Niladri24dutta** [comment]
@thinkingserious  Hi there just checking if the shirts have been shipped yet because I have not received any call from customs.

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

Checking ...

**Comment by Niladri24dutta** [comment]
Hi @thinkingserious Thanks . can you please let me know here if you get any update?

**Comment by thinkingserious** [comment]
HI @Niladri24dutta,

Yes, will do.

**Comment by Niladri24dutta** [comment]
@thinkingserious Hi , Did you get any update? Please let me know if anything is required from my end. I am just little anxious here, hope you can understand.

**Comment by thinkingserious** [comment]
HI @Niladri24dutta,

Your swag is definitely on order and there is nothing further required on your end.

I have not yet received the details from our swag provider though, but once I do, I will let you know.

Thanks!

Elmer

**Comment by Niladri24dutta** [comment]
Thanks for the update.

**Comment by thinkingserious** [comment]
Hi @Niladri24duttal,

I have discovered that your shipment is on hold because the Hacker and Contributor pins are out of stock and we are awaiting a new order. We don't currently have a time frame just yet.

If you like, we can go ahead and send you your T-Shirt and stickers without the pins. Or would you rather wait?

Thanks!

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
hi @thinkingserious  Thanks for replying, is it possible to send the Hacker and Contributor pins separately later on? if not then it's also fine for me if you can send the T Shirt and stickers without the pins.

Thanks

**Comment by thinkingserious** [comment]
Hello @Niladri24dutta,

We can not send them separately. I should know soon when we can restock the pins. Would you like to wait a few more days?

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
Hello @thinkingserious  yes I can wait for few days but I will be on vacation from tomorrow  and will return on 7th September so I will not be able to collect the swag in this time. If the package arrives after 7th September then no issue but I hope it wont be much delay than that.

**Comment by thinkingserious** [comment]
Thanks for the update @Niladri24dutta,

I'm still unsure of the pin status and I might not know until later in the week. How about we re-connect when you come back from vacation?

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
@thinkingserious  ok we can connect once I come back. But I am also fine if you can send the T shirts without the pins later next week.

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

Looks like I'll have an update on the pins tomorrow. I'll loop back with you then.

**Comment by Niladri24dutta** [comment]
@thinkingserious  ok thanks

**Comment by Niladri24dutta** [comment]
@thinkingserious  Hi , Did you get any update about the pins this week? Actually I will be relocating to a different city next month hence it will be difficult for me to collect it in my new changed address as I will be busy this time.

**Comment by thinkingserious** [comment]
I have just checked again today and we are still awaiting finalization of the pins. Would you like us to go ahead and send you the other swag or can you wait a few more days?

**Comment by Niladri24dutta** [comment]
@thinkingserious can you please send the other swag if possible as I already mentioned my current situation above. It will be great help. Thanks

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

I have informed them of your decision and asked to send your swag ASAP without the pin.

**Comment by Niladri24dutta** [comment]
@thinkingserious  thank you so much

**Comment by Niladri24dutta** [comment]
@thinkingserious  thanks for your help , I received an email today regarding the dispatch but it says it might be delayed due to current weather condition.

**Comment by Niladri24dutta** [comment]
@thinkingserious hi , sorry for getting back to you again but I checked the T shirts were dispatched 11 days ago and there is no update in the USPS postal service after 16th September(which was showing in transit) . I haven't received them yet.I am not finding any other way to track the package.Can you please help me with this?

**Comment by thinkingserious** [comment]
Hi @Niladri24dutta,

I've reached out to our swag vendor to see if there is anything we can do on our side.

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
@thinkingserious  hi there, Did you get any update from the vendor regarding this? I am still seeing it the last update on 16th September  regarding the package in USPS portal. I wish I could receive it before my mother's birthday :)

**Comment by thinkingserious** [comment]
Hello @Niladri24dutta,

Not yet, but as soon as I do, I will let you know. 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @Niladri24dutta,

Here is the information I received from our vendor:

> Because of the destination in India we don’t see tracking beyond the date that it left the US. The Indian Post Office doesn’t provide visibility to final destination for USPS packages.
>  
> Packages to some parts of India can take 4-6 weeks for delivery. The India post office may be able to help him track it with this number after it lands in country, although I’m not sure if they have any better visibility on their end: UA644597019US
>  
> It’s definitely en route, departed Chicago last week, and will likely arrive in the next week or two.

I hope that helps. 

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
@thinkingserious  thanks I will look into it.

**Comment by Niladri24dutta** [comment]
@thinkingserious  can you please let me know after discussing with the swag provider that if it has reached India yet? If yes then is it pending with Customs? I had a discussion with India post as they are not aware of this package . The USPS tracking id does not work here.

**Comment by thinkingserious** [comment]
@Niladri24dutta,

Did you receive the package? There is no further information on our side, unfortunately.

**Comment by Niladri24dutta** [comment]
@thinkingserious  Unfortunately not yet, I tried to reach USPS but they said it's still under customs. Already 6 weeks over and I have almost given up my hope for it

**Pull request merged**
