### PR TITLE
Fix #425: Implement IEquatable for EmailAddress

### LINKED ISSUE #425: Impement IEquatable on EmailAddress to Filter Duplicates
#### Issue Summary

By implementing _IEquatable<T>_ on _EmailAddress_ you'd be able to filter out duplicate emails when calling methods such as _AddTo(s)_, _AddCC(s)_, and _AddBCC(s)_.

**IEquatable Implementation**
```
public class EmailAddress : IEquatable<EmailAddress>
{
	public EmailAddress()
	{
	}

	public EmailAddress(string email, string name = null)
	{
		this.Email = email;
		this.Name = name;
	}

	[JsonProperty(PropertyName = "name")]
	public string Name { get; set; }

	[JsonProperty(PropertyName = "email")]
	public string Email { get; set; }

	public bool Equals(EmailAddress other)
	{
		if (other == null) 
		{
			return false;
		}			
		return (this.Email == other.Email);
	}
	
	public override bool Equals(Object obj)
	{
		if (obj == null)
		{
			return false;
		}
		var email = obj as EmailAddress;
		return Equals(email);
	}
	
	public override int GetHashCode()
	{
		return this.Email.GetHashCode();
	}
	
	public static bool operator == (Email emailOne, Email emailTwo)
	{
		if (((object)emailOne) == null || ((object)emailTwo) == null)
		{
			return Object.Equals(emailOne, emailTwo);
		}
		return emailOne.Equals(emailTwo);
	}
	
	public static bool operator != (Email emailOne, Email emailTwo)
	{
		if (((object)emailOne) == null || ((object)emailTwo) == null)
		{
			return !Object.Equals(emailOne, emailTwo);
		}
		return !emailOne.Equals(emailTwo);
	}
}
```

**Sample: SendGridMessage.AddTo() Taking Advantage of the IEquatable**

```
public void AddTos(List<EmailAddress> emails, int personalizationIndex = 0, Personalization personalization = null)
{
	if (personalization != null)
	{
                // Using Union in place of AddRange
		personalization.Tos.Union(emails);
		if (this.Personalizations == null)
		{
			this.Personalizations = new List<Personalization>();
			this.Personalizations.Add(personalization);
		}
		else
		{
			this.Personalizations.Add(personalization);
		}

		return;
	}

	if (this.Personalizations != null)
	{
		if ((personalizationIndex != 0) && (this.Personalizations.Count() <= personalizationIndex))
		{
			var p = new Personalization();
			this.Personalizations.Insert(personalizationIndex, p);
		}

		if (this.Personalizations[personalizationIndex].Tos == null)
		{
			this.Personalizations[personalizationIndex].Tos = new List<EmailAddress>();
		}

                // Using Union in place of AddRange
		this.Personalizations[personalizationIndex].Tos.Union(emails));
		return;
	}

	this.Personalizations = new List<Personalization>()
	{
		new Personalization()
		{
                        // Get rid of any duplicates with Distinct
			Tos = emails.Distinct()
		}
	};
	return;
}
```

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.6.1

### PR DESCRIPTION
**Pull request by Kevek**
This simply implements IEquatable for EmailAddress. 

If you would like me to modify the users of EmailAddress so that they are unique I would be happy to.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=533) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=533) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=533) it.</sub>

**Comment by thinkingserious** [comment]
Hello @Kevek,

It would be great if you could ensure that we have all unique EmailAddress objects (the email portion must be unique), since we do not allow duplicate emails in the request body.

Thank you!

With Best Regards,

Elmer

**Comment by Kevek** [comment]
Will do. Give me a few days to get back at it, just had a new addition to the family!

I'll make sure the consumers of EmailAddress use .Distinct or something to ensure the Lists contain unique entries. I cannot remember offhand, but I'll also look to add some tests that check for this sort of thing as well.

**Comment by thinkingserious** [comment]
@Kevek

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hi @Kevek,

Just checking back in with you as this PR just came up on our backlog to merge.

**Comment by thinkingserious** [comment]
Closing until PR feedback is addressed.

**Pull request closed without merging**
