### PR TITLE
Issue 774

### PR DESCRIPTION
**Pull request by drabiu**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- no need to change the readme.md file
- no need to write new tests
-change returns summary descritpions
-change returns to responseHttpMessage
-fixed example code

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=854) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=854) before we can accept your contribution.<br/><hr/>**PGS-SOFT\mdrab** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=854) it.</sub>

**Comment by jnyrup** [comment]
Please be aware that it a breaking change to change the return type.

**Comment by aevitas** [comment]
While it is a breaking change, I reckon it is a good change to be made in a future major version. Currently, the `Response` type provides less information about the response than the `HttpResponseMesage` it wraps, plus you lose the convenience extension methods `Microsoft.Rest` provides.

**Comment by thinkingserious** [comment]
Hello @drabiu, @aevitas,

I'm closing this one, since I think that #1019 will resolve this issue.

If you have further feedback, please free to comment here and re-open or on #1019. Thanks!

**Pull request closed without merging**
