### PR TITLE
Prerequisites

### PR DESCRIPTION
**Pull request by Rick-Anderson**
It should be .NET Framework 4.6:
https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @Rick-Anderson,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by SendGridDX** [comment]
Hi @Rick-Anderson,

Thanks for taking the time to contribute!

Just a quick question. Why do you want to change the prerequisites? We also release a .dll that is [compatible with 4.5.2 and above](https://github.com/sendgrid/sendgrid-csharp/blob/master/nuspec/Sendgrid.9.0.12.nuspec#L18).

With Best Regards,

Elmer

**Comment by Rick-Anderson** [comment]
The original seems to state .NET 4.5.2 implies support of  .NET Core (no version mentioned).
According to [.NET Platforms Support](https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support), .NET Standard 1.3 doesn't support .NET Core 1.0 and supports .NET Framework 4.6 and higher.

Perhaps I should change it to : 
Supports  .NET 4.5.2 and higher and .NET Core 1.0 and higher. 

cc @mairaw

**Comment by mairaw** [comment]
Those arrows are confusing. .NET Standard 1.3 does support .NET Core 1.0.

**Comment by Rick-Anderson** [comment]
@mairaw  but  .NET Standard 1.3  doesn't support   .NET 4.5.2
So I don't know how they accomplished that or how to word that.

**Comment by SendGridDX** [comment]
@Rick-Anderson,

We compile against [.NET Standard 1.3 **and** .NET 4.5.2](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/project.json#L25).

So perhaps we should simply say:

.NET version 4.5.2 and above, including .NET Core

or even simpler:

.NET version 4.5.2+

That said, I think some people are specifically looking for .NET Standard or .NET Core support, that is why I specifically called those out.

**Comment by mairaw** [comment]
So how about saying 
".NET version 4.5.2 and higher or .NET Core 1.0 and higher (this library targets .NET Standard 1.3)."?

**Comment by thinkingserious** [comment]
@mairaw 

That is an epic sentence :)

Maybe it might be more digestible if we create bullet points:

* .NET version 4.5.2 and higher
* .NET Core 1.0 and higher
* .NET Standard 1.3 support

**Comment by SendGridDX** [comment]
@Rick-Anderson,

Do you want to revise the pull request or shall I make the changes myself? I'm OK with either way. Thanks!

**Comment by Rick-Anderson** [comment]
@SendGridDX  you make the changes.

**Pull request closed without merging**
