### PR TITLE
adds method to verify that content doesn't contain forbidden secrets

### LINKED ISSUE #565: Prevent secrets from sending in email
Add a method that will check the content of the email before sending, to make sure that specific strings or patterns are not included.
For example, SG API keys look like this: SG.[a-zA-Z0-9_].[a-zA-Z0-9\-]
So the function could take a list of regex or specific strings to compare against. If a string is found, the mail/send should throw an exception

### PR DESCRIPTION
**Pull request by SaiKai**
this should fix #565

example : 
var sg = new SendGridClient(apikey);
// rule to check if content contains SendGrid api keys
sg.AddContentVerifyRegexRule(".*SG\\.[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+.*");
// rule to check if content contains the string "secret"
sg.AddContentVerifyTextRule("secret");
var response = await sg.SendEmailAsync(msg); // this will throw an exception, if content matches given rules

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=574) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=574) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=574) it.</sub>

**Comment by mbernier** [comment]
@SaiKai

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @SaiKai,

Do you mind adding some usage documentation [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md)? Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Closing until PR feedback is addressed.

**Pull request closed without merging**
