### PR TITLE
Change default literals to C# 7 style literals

### PR DESCRIPTION
**Pull request by aevitas**
Small PR that changes `default(T)` usages to C# 7 style `default` literals.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
-  change `default(T)` usages to C# 7 style `default` literals

### CODE REVIEW

**Comment by RodgerLeblanc** [comment]
This code goes against the CONTRIBUTING.md prerequisites, as C#7 is available on Visual Studio 2019+. It's possible to install C#7 on Visual Studio 2017, but it's not something a new contributor might know how to do.

Currently, if I build master on VS2017, it works. If I build your project on VS2017, I get those : 
image

Three options : 
* Not use C#7 features
* Upgrade CONTRIBUTING.md to reflect that VS2019 is now needed
* Add steps in CONTRIBUTING.md to add C#7 for contributors with VS2017

**Comment by aevitas** [comment]
Good point. I'm compiling using VS2019 and the language version is inferred. @thinkingserious what do you think? Should the contribution guidelines be updated to encourage use of VS2019?

**Comment by thinkingserious** [comment]
Hello @aevitas,

My apologies for the super delayed response. I agree that we should change the contribution guidelines to encourage use of VS2019. 

Also, could you please help resolve the branch conflicts so we can get this one merged? Thank you!

With best regards,

Elmer

**Comment by JenniferMah** [comment]
Closing until PR feedback and merge conflicts are addressed.

**Pull request closed without merging**
