### PR TITLE
Corrected list all recipients documentation Fixes #351

### LINKED ISSUE #351: USAGE.md - Retrieve all recipients on a List, list_id should not be part of queyparams
There is an error in Retrieve all recipients on a List example in USAGE.md document. The parameter list_id should not be part of the queryParams, otherwise you get an error (BadRequest) saying that list_id is not part of the custom filters. Removing list_id from queryParams fixes the issue.

### PR DESCRIPTION
**Pull request by Gimly**
Fixed the example query for list all recipients to be the same as the one in SendGrid's documentation. Removed the list_id parameter that was incorrect.

Fixes #351

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=527) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=527) it.</sub>

**Comment by mbernier** [comment]
@Gimly did you find that the list_id param was not actually the issue, but the page size was the issue?

The original page size being 1 doesn't make sense, I just want to verify that I am following your change here.

**Comment by thinkingserious** [comment]
Hello @Gimly,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Gimly** [comment]
@mbernier Yes, list_id didn't make sense in that call so I removed it, that fixed the issue. And since I was modifying the doc for that,I thought it would make sense that it was the same as the Sendgrid api. That's why I also modified the page_size.

**Pull request merged**
