### PR TITLE
Fix group targetframeworks in nuspec

### LINKED ISSUE #742: Mismatching dependencies between csproj and nuspec
I was excited to see #601 was merged into v9.10.0. Although it looks like the nuspec that is being used has an old set of frameworks and dependencies, which brings it back to the same point as previous in #601 + different target frameworks being used between the nuspec and csproj.

Based off of the current csproj:
* net40 target framework has returned
* net452 target framework is missing
* System.Net.Http v4.3.3 is still required

Current view from Nuget:
image

### PR DESCRIPTION
**Pull request by bmeredith**
# Fixes #742

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
This correctly aligns the nuget dependencies between the nuspec and csproj files.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=743) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=743) it.</sub>

**Comment by xt0rted** [comment]
Wouldn't it be easier to run `dotnet pack` against the `.csproj`? That should remove the need for a `.nuspec` file and then the frameworks & dependencies only need to be managed in one spot instead of two.

**Comment by thinkingserious** [comment]
Hi @xt0rted,

That sounds good to me. But I'm thinking some still may rely on the .nuspec?

I'm not too sure what `dotnet pack` does, so I'll give it a go as soon as this comes up on my backlog.

Thanks as always for your support and contributions!

With Best Regards,

ElmWith Best Regards,

**Comment by jnyrup** [comment]
@thinkingserious Using `dotnet pack` also puts a `nuspec` file in the `nupkg` file. 

Running `dotnet pack SendGrid.csproj` gives

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>SendGrid</id>
    <version>9.10.0</version>
    <authors>SendGrid</authors>
    <owners>SendGrid</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.5.2">
        <dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard1.3">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Runtime.Serialization" targetFramework=".NETFramework4.5.2" />
    </frameworkAssemblies>
  </metadata>
</package>
```

But that really should be handled in another issue/PR

**Comment by bmeredith** [comment]
Closing as #892 fixed this issue.

**Pull request closed without merging**
