### PR TITLE
Fix-744

### LINKED ISSUE #744: Update Newtonsoft.Json dependency version
Are there plans to update this package to use more recent versions of the newtonsoft.json package?  It fails if any version above 9.0.1 is installed.

### PR DESCRIPTION
**Pull request by fabricioveronez**
I updated Newtonsoft.Json dependency version

Fixes #744

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=780) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=780) it.</sub>

**Comment by thinkingserious** [comment]
@fabricioveronez,

Thanks for the PR!

Is there a reason we want to lock into version 11. How about requiring latest version of 9.X, 10.X and 11.X?

With Best Regards,

Elmer

**Comment by jnyrup** [comment]
@thinkingserious  As a library, you should strive to require the lowest possible version of Newtonsoft.Json.
Before merging any of these NewtonSoft.Json upgrade, it should be clarified exactly what problem an upgrade solves.

As many packages rely on Newtonsoft, it's quite likely that the issue your users suffer should be solved with either SDK style csproj or assembly binding redirects.

A valid reason for referencing a new newtonsoft.Json would be if a newer version of newtonsoft.json has an API/ABI breaking change.

Just upgrading to newest newtonsoft.json could harm users, who for some reasons cannot upgrade newtonsoft.json

**Comment by childish-sambino** [comment]
I agree with the comment by @jnyrup and am closing this request.

**Pull request closed without merging**
