### PR TITLE
Update serializer settings to include default values #273

### PR DESCRIPTION
**Pull request by owre**
Changed json serializer settings to include default values to fix issue #273 
The default implementation removes the enable flags from tracking settings if set to false. Resulting in: 
The click_tracking(etc) enable parameter is required.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Awesome!

Could you please sign our CLA to get this merged? https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by owre** [comment]
I have signed the CLA and sent it to dx@ 
Cheers

**Comment by thinkingserious** [comment]
I will need to give this one some more thought. 

The failing TestHelloEmail test happens because your change allows `"send_at":0` to be a part of the returned JSON object because the default value for a long is zero. We need to ignore unset values, but in C# all variables are initialized.

I'm thinking we need to instead build the object piece by piece and then deserialize that object vs trying to deserialize the entire Mail object and figuring out which values to ignore properly.

**Comment by owre** [comment]
How about making it nullable? That way it wont be included.

**Comment by thinkingserious** [comment]
I was thinking about trying this: https://msdn.microsoft.com/en-us/library/53b8022e(v=vs.110).aspx

**Comment by thinkingserious** [comment]
I like the nullable idea also.

**Comment by owre** [comment]
Good idea http://www.newtonsoft.com/json/help/html/conditionalproperties.htm

I think a nullable property would be easier. Is it any more property that should not be serialized with its default value?

**Comment by thinkingserious** [comment]
Generally, if you don't set a value, then it should not show up.

**Comment by thinkingserious** [comment]
Seems like if we go the nullable route, we need to initialize the values to null. Looking at the failed test, it looks like we still get `"send_at":0`

**Comment by owre** [comment]
I missed to make sendAt in mail nullable. Fixed :)

**Comment by thinkingserious** [comment]
Nice work! I'm hoping to have some time to review today.

**Comment by thinkingserious** [comment]
@owre,

I just put in a pull request on your fork that adds in the rest of the nullable fixes, plus an additional unit test.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-csharp/pull/293

**Comment by thinkingserious** [comment]
@owre,

Please shoot us an email to dx@sendgrid.com with your mailing address and T-shirt size so we can send you a token of our appreciation.

**Comment by owre** [comment]
Thank you very much! :)

**Pull request closed without merging**
