### PR TITLE
Fix runtime warnings 11 #632

### PR DESCRIPTION
**Pull request by sidkcr**
# Fixes # 

- Fixed runtime warnings 11 - #632

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them. 
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified 

### Short description of what this PR does:

- This change eliminates all build warnings.

 
---- 
Hello,

I am new to GitHub and this is my first pull request. Please review this pull request. I am not sure about the XML documentation I've added for SendAsync method is accurate. Please guide me.

Thanks,
Siddharth

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=699) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=699) before we can accept your contribution.<br/><hr/>**siddharth.kochar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=699) it.</sub>

**Comment by thinkingserious** [comment]
Hello @sidkcr,

Were you having trouble with the CLA?

**Comment by sidkcr** [comment]
Hello @thinkingserious 

I have accidentally committed the code with another email address which I cannot share on GitHub. So I have closed the pull request. 

Later, I understand this issue is already referenced and fixed in another pull request.  
So I didn't open new PR for this issue.

I have just started to contribute on GitHub.

**Comment by thinkingserious** [comment]
Thanks @sidkcr!

**Pull request closed without merging**
