### PR TITLE
Created a tutorial to deploy a simple Hello Email app on Heroku with ASP.NET Core

### PR DESCRIPTION
**Pull request by zchaudhry11**
#539

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=593) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=593) it.</sub>

**Comment by mbernier** [comment]
@zchaudhry11

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @zchaudhry11,

Thank you for the PR and my apologies for the delayed code review.

Upon deploy, I receive the following error:

```bash
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  Restored /tmp/build_2ffed336_/aspnetcoreapp.csproj (in 5.76 sec).
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/tmp/build_2ffed336_/aspnetcoreapp.csproj]
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed
```

Please let us know what we need to adjust to get this working on Heroku.

Thanks!

With best regards,

Elmer

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.

**Pull request closed without merging**
