### PR TITLE
Add support for AMP MIME parts and fix sorting

### PR DESCRIPTION
**Pull request by DarkFox**
Adds MimeType.Amp and refactors the sorting code that caused
AMP parts to be sorted last, causing emails to display incorrectly
in some clients.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds the MIME type for AMP For Email to MimeType.
- Adds AMP MIME part to serializer sorting, between plaintext and HTML.
- Fixes the sorting code in the serializer, which previously just put Text and HTML parts at the top, but not necessarily in the right order.

If you have questions, please send an email to [Twilio Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @DarkFox,

Thank you for the PR!

Which email clients are effected by this issue?

We also need to check if the new mime type ordering [does not break](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L43) existing email clients.

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @DarkFox,

Just checking in. If you no longer have time to move this one forward, please let us know.

Thanks!

With best regards,

Elmer

**Comment by DarkFox** [comment]
Hi @thinkingserious,

Unfortunately I'm no longer with Trustpilot, and as such have no further interest in this. @irq might be able to take over this PR, if they're still interested in pursuing this.

Best regards,
Martin

**Comment by irq** [comment]
@DarkFox Thanks for pinging me :)

@thinkingserious 
As far as I remember it broke in Gmail web client when trying to add the amp content.
We still have an interest in this, but since the project was just an old prototype which is not running anymore I don't currently have a way (or the knowledge) to work on this. If/when we start up the project again I could take a look.

**Comment by thinkingserious** [comment]
Thank you @irq! 

And thanks to @DarkFox for the introduction!

**Comment by thinkingserious** [comment]
Hello @irq,

Just checking in! 

I've changes the labeling on the ticket in case someone else would like to give it a shot. We also are adding this issue to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
Closing as there's been no progress on this in a while. Feel free to create a new issue and link this PR if it's still an issue along with the steps needed to recreate.

**Pull request closed without merging**
