### PR TITLE
USE_CASES.md fix #353 issue

### LINKED ISSUE #353: USAGE.md - missing Recipient Search with conditions [POST] example
There is missing example in USAGE.md document to search Recipients with conditions.

``` c#
   string data= @"{
      'conditions': [
        {
            'field' : 'last_name',
            'value': 'test last name',
            'operator': 'eq',
            'and_or': ''
        }]
    }";
    dynamic response = await sg.client.contactdb.recipients.search.post(requestBody: data);
    Console.WriteLine(response.StatusCode);
    Console.WriteLine(response.Body.ReadAsStringAsync().Result);
    Console.WriteLine(response.Headers.ToString());
    Console.ReadLine();
```

### PR DESCRIPTION
**Pull request by kostyaHrytsyuk**
Add RecipientSearch with conditions[POST]

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=604) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=604) it.</sub>

**Comment by mbernier** [comment]
@kostyaHrytsyuk we can't do anything with your PR until the CLA is signed!

**Comment by thinkingserious** [comment]
@kostyaHrytsyuk

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request closed without merging**
