### PR TITLE
750 contactdb helpers

### LINKED ISSUE #750: Create helper methods for the /contactdb endpoint
#### Issue Summary

Please see `USE_CASES.md` for current example of existing helper methods.

You may find simple example code for all of the `/contactdb` endpoint functionality in the `USAGE.md` file under `CONTACTDB` in the Table of Contents. Complete interactive documentation can be found [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* helper methods are created for all documented /contactdb functionality
* tests pass locally, in Travis CI and using Docker
* updated `USE_CASES.md` or `/use-cases` documentation

### PR DESCRIPTION
**Pull request by Gimly**
# Fixes #750

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds a helper class and interface that allows to simplify the use of the Contacts DB API

### CODE REVIEW

**Comment by Rody66** [comment]
Hi @Gimly ! It's really useful feature please keep going.

**Comment by Gimly** [comment]
@Rody66 I had forgotten about this PR, I was waiting for some feedback on what was done already. I'll try to to get back to it and see what needs to be done to finish it

**Comment by Rody66** [comment]
Thank you! I'll be waiting for these helpers.10:30, 6 июня 2019 г., Xavier Hahn <notifications@github.com>:@Rody66 I had forgotten about this PR, I was waiting for some feedback on what was done already. I'll try to to get back to it and see what needs to be done to finish it

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by thinkingserious** [comment]
Since there has been no activity on this issue since March 1, 2020, we are closing this issue. If you are still interested in moving this PR forward, please feel free to reopen. Thank you!

**Pull request closed without merging**
