### PR TITLE
Initial removal of dynamic with some Client refactoring

### PR DESCRIPTION
**Pull request by thinkingserious**

### CODE REVIEW

**Comment by jduncanator** [comment]
This looks like a step in the right direction. Once we get dynamics out of the picture, we can start addressing other areas! +1 from me.

**Comment by thinkingserious** [comment]
Hello @thinkingserious,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team DX

**Comment by jduncanator** [comment]
@thinkingserious Not sure if serious? :p

**Comment by thinkingserious** [comment]
Ha! That is a bug in our GitHub automator. Glad you pointed that out :)

**Comment by thinkingserious** [comment]
@jduncanator,

Fixed the bug. I forgot to apply the exclusions list to the case when we merge a pull request of someone internal to SendGrid. Thanks again for the heads up!

**Comment by jduncanator** [comment]
@thinkingserious No problem! Glad to see you got the PR merged!

**Pull request merged**
