### PR TITLE
SendAsync with response returned

### PR DESCRIPTION
**Pull request by MarcelloCarreira**
This will send the message Async, and will return a string after is completed.
If the delivery is ok, the string will be "OK" (from the HttpStatusCode)
If there is an error, the error will be catch and the string will show the error in this format:
Status Code: [HttpStatusCode]. Errors returned by the API: [error1; error2; etc;]
Example of error:
Status Code: BadRequest. Errors returned by the API: Missing subject;
Status Code: BadRequest. Errors returned by the API: invalid API Key;

Modifications to avoid DeadLocks on awaiting task when running from razor.

cshtml razor example file included.

### CODE REVIEW

**Comment by MarcelloCarreira** [comment]
** Updated Text ***

Modifications to avoid DeadLocks when waiting tasks running from razor code: 
In the current branch (including master and bugfixes), when you try to deliver a message from razor code, you have to do one of the following:  - not use task + await and by doing so the task will execute, but with no assurance of it been completed because it´s not awaited (for example using only transportWeb.DeliverAsync(sendGridMessage)); - Or using the task + await, but in this case the two things can happen depending on how you call the class, - you receive a not async call error; or, you can have the message delivered to the api, but the task never finishes because it´s in another context. Anyway you have no control of the real delivered state.

In this fork I included another method, DeliverAsyncReturn. So by calling transportWeb.DeliverAsyncReturn(sendGridMessage) you get a returned string with the httpstatuscode. To keep in the same context and avoid the deadlock, the await is configured, so it can return the response correctly. The call is something like string response = await transportWeb.DeliverAsyncReturn(sendGridMessage).ConfigureAwait(continueOnCapturedContext: false); the call also can just expect the result of the task, so it should look like response = transportWeb.DeliverAsyncReturn(sendGridMessage).Result. By doing so, the call will still be async, as it expects the end result to return.

In the examples I included SendGridSendAsync.cs, a class that puts the credentials or apikey to the transport and send the message async, expecting the results. It also catch all Exceptions and InvalidApiRequestException and put them into a string, so it´s easier to the user see what´s going on.
Also there is a .cshtml razor page. The end user would collect data for sending a message on db or an inpage form, then can send the message and save back the result to the db or show the user if the message reached the api (showing ok, or the error) easily.

**Comment by brandonmwest** [comment]
Thanks for the PR! We've had similar code in the Example project in the sln, but I realize most people probably never actually look at that. I didn't want to presume to handle the task for people, but I think you're right that it should be default behavior based on the number of issues it causes. I'll take a look next week when I'm back from holiday :)

**Comment by MarcelloCarreira** [comment]
Ok, thank you very much. If necessary we can move the handling from examples and incorporate it into de main dll. Give it a look and tell me what you think. Have a nice holiday! Marcello

**Comment by kowsheek** [comment]
Any timeline on when this PR is going to be accepted and published?

**Comment by thinkingserious** [comment]
@MarcelloCarreira,

Thanks for the pull request!

We have completely re-written this library and will be moving from beta to GA in weeks. You can check out the new library here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta. If you would like to contribute this pull request on the new library, I will need you to make your pull request against the v3beta branch and we will need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla

Thanks for your support!

With Best Regards,

Elmer

**Pull request closed without merging**
