### PR TITLE
Fixed virtual bug

### LINKED ISSUE #697: Can't add custom header, MakeRequest not virtual
I was trying to add a header to the httpcall made by SendEmailAsync. By looking to the SendGridClient class, over the MakeRequest is written : "Make the call to the API server, override for testing or customization", but the call isn't virtual. 

Is there any other way to add an header to the call by using SendEmailAsync ? 
Am I missing something here ?

#### Technical details:
sendgrid-csharp Version: 9.9.0
Platform ASP.NET Core
netstandard2.0

### PR DESCRIPTION
**Pull request by psboies**
# Fixes # 

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Fix for issue #697 https://github.com/sendgrid/sendgrid-csharp/issues/697#event-1681681007
- Added virtual tag to a method that should be virtual.
- Tested, it fixes the bug we have discussed in issue #697

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=702) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=702) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=702) it.</sub>

**Comment by thinkingserious** [comment]
This is awesome @psboies! This is on our backlog for a merge.

**Comment by psboies** [comment]
Thansk @thinkingserious . Have a great day!

**Comment by thinkingserious** [comment]
Hello @psboies,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
