### PR TITLE
Update JSON.NET to latest version

### LINKED ISSUE #744: Update Newtonsoft.Json dependency version
Are there plans to update this package to use more recent versions of the newtonsoft.json package?  It fails if any version above 9.0.1 is installed.

### PR DESCRIPTION
**Pull request by Fraaankes**
# Fixes # 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
Fixes #744 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=748) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=748) before we can accept your contribution.<br/><hr/>**Frank** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=748) it.</sub>

**Comment by Fraaankes** [comment]
Im still fighting a bit with this. So easy in theory, but .net standard 1.3 turns out to a tricky target.
Even more annoyingly it all `dotnet build`s + `dotnet pack`s perfectly locally on .net core 2.1, so i dont really have a good environment to repro on.

**Comment by Jacrys** [comment]
The issue here seems to be that you are targeting netstandard 1.3, but are trying to add support for Newtonsoft v 11.0.2 and looking through the Newtonsoft change logs, 11.0.1 added netstandard 2.0.  It looks like from looking at this that this can be fixed by specifically targeting 10.0.1, which was the last version to target netstandard 1.3. Newtonsoft 10.0.2 updated dependencies to netstandard 1.6.

**Comment by Jacrys** [comment]
Also, @Fraaankes, I notice that you have changed the Net Framework 4.5 files to use 11.0.2, and 11.0.2 targets netstandard 2.0 so the framework support would need to be increased to 4.6.1[1](https://github.com/dotnet/standard/blob/master/docs/versions.md) to support it. I am making some commits and a PR against your fork so you can merge them in and update this PR.

**Comment by Fraaankes** [comment]
Thanks you for pitching in @Jacrys it is much appreciated. I merged in your changes, but unfortunately it still doesnt look like the build is happy.
I didnt look too closely at the changelog for json.net as they are usually the gold standard for maintaining backwards compat, but maybe not in this case :)

**Comment by thinkingserious** [comment]
Looks like something [like this](https://github.com/dotnet/standard/issues/542#issuecomment-339328208) is needed. But I'm not quite sure why.

**Comment by thinkingserious** [comment]
Hello @Fraaankes,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Jacrys** [comment]
It turns out that netstandard20 was added to the targets.  If you remove that, it builds fine, at least on my replicant of the Travis env. I have an open pull request against his branch to fix the issue.

**Comment by Fraaankes** [comment]
Hey guys, sorry for the delay.
Ill try to merge your removal of .net standard 2 (just to see if it builds), but since it was already a target before this update, wouldn't it be considered a breaking change for all .net core clients ?

**Comment by Jacrys** [comment]
OK, after much trial and error, I think I have this narrowed down.  The issue seems to be when I reference a netstandard2.0 build of Newtonsoft from the netstandard2.0 build pathway.  This behaviour points to a possible bug with Newtonsoft, but I am unsure without doing some more testing.  I have pushed a version that reverts to all of the changes @Fraaankes initially made but limits the netstandard2.0 pathway to 10.0.3.  This updates to newer version support, but stays out of the "here may be dragons" netstandard2.0 death spiral in which we find ourselves.  In the meantime, I will look into this further and do a few more use cases to see if I can repro the observed behaviour on a vanilla Library project using netstandard2.0 and Newtonsoft 11.0.2.

**Comment by Jacrys** [comment]
I am sorry for the wild goose chase I kind of led us down.  This is part of learning I guess... 😅

**Comment by Fraaankes** [comment]
@Jacrys  Well would you look at that, I do believe we have compilation ! 👯‍♂️ Now to see whats up with that unit test now.

**Comment by Jacrys** [comment]
I figured out the issue with the failing build when targeting netstandard2.0 and Newtonsoft >=11.0.1. Looking through the logs for Newtonsoft, the 2.0 build configuration required changing how they used certain functionalies, meaning the netstandard 1.x versions and the netstandard 2.x versions are completely different.  The netstandard 2.x versions use 2.0 specific functionalities and are therefore tied to the netstandard 2.x buildchain.  Even though the SendGrid library targets netstandard2.0 currently, it does not use any of the netstandard2.0 functionality.  Therefore, the 1.x SDK can still build it correctly since 2.0 extends 1.x.  In order to build the netstandard2.0 target with Newtonsoft.Json >= 11.0.2, the Travis CI toolchain will need to be changed.  I have pushed a new version that will base TravisCI on the 2.0.0 SDK and it should pass the build as well. Unless @thinkingserious or someone else at @SendGridDX can think of a reason we would not want to do this.

**Comment by Jacrys** [comment]
I figured out the issue with the failing build when targeting netstandard2.0 and Newtonsoft >=11.0.1. Looking through the logs for Newtonsoft, the 2.0 build configuration required changing how they used certain functionalies, meaning the netstandard 1.x versions and the netstandard 2.x versions are completely different.  The netstandard 2.x versions use 2.0 specific functionalities and are therefore tied to the netstandard 2.x buildchain.  Even though the SendGrid library targets netstandard2.0 currently, it does not use any of the netstandard2.0 functionality.  Therefore, the 1.x SDK can still build it correctly since 2.0 extends 1.x.  In order to build the netstandard2.0 target with Newtonsoft.Json >= 11.0.2, the Travis CI toolchain will need to be changed.  I have pushed a new version that will base TravisCI on the 2.0.0 SDK and it should pass the build as well. Unless @thinkingserious or someone else at @SendGridDX can think of a reason we would not want to do this.  It should have no merge conflicts with your test changes @Fraaankes.

**Comment by thinkingserious** [comment]
Hello @Fraaankes,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @Fraaankes,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by tasdpp** [comment]
Is this issue going to get resolved?

**Comment by Jacrys** [comment]
I will take a look when I get a chance to see what the breaking issues are.  I have some free time coming up.

**Comment by jnyrup** [comment]
This seems to be a duplicate of #780 which only tries to upgrade newtonsoft.json and not multiple changes at once.

**Comment by Jacrys** [comment]
I fail to see how a PR that is older can be a duplicate of a PR that is newer.  All changes made to files were made to fix breaking build changes that occurred as part of the change.  Which, as you can see from the failing status of both Travis checks is still occurring, though we have fixed the issue with actually being able to pull the image, If you review the PR changes, you will see the only changes made to the files save those made by Fraankes to the Integration Tests (which were made to fix a failing Travis check, as tests are part of the Travis pipeline, and merges are blocked until Travis build completes) are changes directly related to upgrading JSON.NET version.

**Comment by jnyrup** [comment]
@Jacrys I'm sorry, that came out wrong and was ignorant to the work being done here.

Instead I'll re-post my comment from #780 here as well

As a library, you should strive to require the lowest possible version of Newtonsoft.Json.
Before merging any of these NewtonSoft.Json upgrade, it should be clarified exactly what problem an upgrade solves.

As many packages rely on Newtonsoft, it's quite likely that the issue your users suffer should be solved with either SDK style csproj or assembly binding redirects.

A valid reason for referencing a new newtonsoft.Json would be if a newer version of newtonsoft.json has an API/ABI breaking change.

Just upgrading to newest newtonsoft.json could harm users, who for some reasons cannot upgrade newtonsoft.json

**Comment by childish-sambino** [comment]
I agree with the comment by @jnyrup and am closing this request.

**Pull request closed without merging**
