### PR TITLE
Strongly typed

### PR DESCRIPTION
**Pull request by Jericho**
- Values returned by methods are strongly typed
- Sensible method names. For example, "Create" instead of "Post".
- All methods are awaitable
- Avoid deadlocks in ASP.NET by making sure all async calls is configured with ConfigureAwait(false)

### CODE REVIEW

**Comment by thinkingserious** [comment]
Very nice Jericho!

I'll be spending some time reviewing this and integrating into our upcoming library refresh.

THANKS!

**Comment by Jericho** [comment]
I just fixed the unit tests but I just wanted to point out that they are not really unit tests since they make actual calls to the SendGrid API. These unit tests should be improved to test our C# code (with mocked httpclient) as opposed to making API calls.

**Comment by Jericho** [comment]
Unit tests are failing because of the following error:
`{"errors":[{"field":null,"message":"authorization required"}]}`

I'm guessing this is due to the fact that "SENDGRID_APIKEY" environment variable is missing from the build machine.

**Comment by thinkingserious** [comment]
You are correct. I thought I fixed that issue though.

In any case, I'm refactoring the unit tests in the new library so that they no longer require a network call. I'm thinking I'll have the integration tests only run locally. The new HTTP client is already refactored in that way with a mocked client: https://github.com/sendgrid/csharp-http-client/blob/master/UnitTest/UnitTest.cs

**Comment by thinkingserious** [comment]
Hi @Jericho,

We've finally gone to beta with our new library and you can check it out here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

We plan to implement strong typing through helpers, see the helper for v3 /mail/send for an example: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/SendGrid/SendGrid/Helpers/Mail/Mail.cs Currently, we've just added the getters/setters in preparation for that.

If you would like to continue contributions, we will need your pull requests to be made against the v3beta branch and we'll need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla Please let me know if you have any questions.

We appreciate your patience and continued support!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for the CLA @Jericho!

Will you be making a new pull request on our v3beta branch or will wait until it gets out of beta in a few weeks?

**Comment by Jericho** [comment]
I am trying to figure out if it’s possible to change the branch for a pull request. Maybe the only solution is to close the original PR and create a new one?? Do you have any suggestion?

**Comment by Jericho** [comment]
Also there is a branch called v3_beta and another one called v3beta. Which one is the right one?

 

 

From: Jérémie Desautels [mailto:desautelsj@hotmail.com] 
Sent: Friday, May 20, 2016 3:20 PM
To: 'sendgrid/sendgrid-csharp' <reply@reply.github.com>; 'sendgrid/sendgrid-csharp' <sendgrid-csharp@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [sendgrid/sendgrid-csharp] Strongly typed (#211)

 

I am trying to figure out if it’s possible to change the branch for a pull request. Maybe the only solution is to close the original PR and create a new one?? Do you have any suggestion?

**Comment by thinkingserious** [comment]
The correct branch is v3beta, thanks for checking!

That branch is a complete rewrite of this library, so I don't think this pull request can be directly mapped.

I'm happy to help figure it out with you, but that would require some time as I'm now in the process of finishing updating all our 7 libraries in support of the v3 /mail/send endpoint and coverage for all v3 Web API calls. That work comes out of beta in a few weeks, so my guess would that I would need at least a few weeks before I can dig in deeper with you. That said, if you come up with any specific questions, please let me know and I'll do my best to answer quickly

Thanks for checking in and for your support!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
I should also note that the only helper that has been implemented so far is for the /mail/send endpoint, which you can find here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta/SendGrid/SendGrid/Helpers/Mail. Strong typing has not been implemented there, but the framework is in place. You would be using a similar strategy for strongly typing any other endpoint.

Please let me know if you have any questions.

**Comment by thinkingserious** [comment]
Now that we are out of beta, I suggest you go ahead make a new pull request against the current version.

Thanks @Jericho!

Please let me know if there is anything I can do to help.

**Pull request closed without merging**
