### PR TITLE
Added template example for sending mail with Mail Helper

### PR DESCRIPTION
**Pull request by antimatter96**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Awesome!

Could you please sign our CLA so we can merge? https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla

**Comment by antimatter96** [comment]
Sent to mentioned email address

**Comment by thinkingserious** [comment]
Thanks!

This one is high in the queue, my best guess is that it will be merged next week.

**Comment by thinkingserious** [comment]
@antimatter96 I've made some suggestions to your pull request here: https://github.com/antimatter96/sendgrid-csharp/pull/1/files

**Pull request merged**
