### PR TITLE
Error exception handling

### LINKED ISSUE #796: Error Exception Handling
#### Issue Summary

To improve the developer experience, we would like to pass back a [summary of the error received](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html) and a link to the appropriate place [in the documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html) to help with troubleshooting. 

#### Acceptance Criteria
 

* When an error is thrown due to a failed request, a summary of that error along with a [link to the appropriate place in the documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html) should be sent back as a JSON object.
* Tests that demonstrate successful functionality

### PR DESCRIPTION
**Pull request by Fabio-Alexander-Bueno**
# Resolves #796  

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [X] I have added in line documentation to the code I modified

### Short description of what this PR does:
Created Error Handler to return a json with a summary of that error and a link to help page.

### CODE REVIEW

**Comment by aroach** [comment]
@thinkingserious question here from @Fabio-Alexander-Bueno about how to inject the API Key for the build

**Comment by thinkingserious** [comment]
Hello @Fabio-Alexander-Bueno,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Fabio-Alexander-Bueno** [comment]
For information only. Updated TROUBLESHOOTING.md

**Comment by thinkingserious** [comment]
Hello @Fabio-Alexander-Bueno,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 7 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by thinkingserious** [comment]
Hello @Fabio-Alexander-Bueno,

Instead of using a live API Key, please have the tests run agains the Prism mock server. Here is [an example](https://github.com/sendgrid/sendgrid-csharp/blob/master/tests/SendGrid.Tests/Integration.cs).

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Replacing with https://github.com/sendgrid/sendgrid-csharp/pull/1019

**Pull request closed without merging**
