### PR TITLE
Refactoring SendGridClient to support inject external managed HttpClient

### LINKED ISSUE #670: SendgridClient constructor issue
I'm trying to provide a DI controlled HttpClient object (singleton) to the constructor of SendgridClient to overcome known socket exhausting issue by reusing the instance of the aforementioned HttpClient.
The first email sends just fine, however the second one fails with this exception:

> InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.

Having done additional research I figured that a single instance of HttpClient allows changing its configuration properties (BaseAddress in particular) only before the 1st connection is made with this instance. Trying to modify BaseAddress property after HttpClient was used causes this exception to be thrown.
Referenced SO post: 
https://stackoverflow.com/questions/42235677/httpclient-this-instance-has-already-started

I went to the source code of SendgridClient and found out that the constructor of SendGridClient calls InitiateClient function which resets the BaseAddress of the underlying HttpClient object every time the SengridClient instance is created:
https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs
Line: 157

On one hand one can register an instance of SendgridClient in a DI container, but it defies the intended purpose of having such constructor overload in SendgridClient class, allowing to provide the existing instance of HttpClient.

One way to fix it could be checking if the provided instance of HttpClient already has its params configured and not overwrite them if so.

### LINKED ISSUE #897: HttpClient should be a static instance, and threadpool expired periodically
Currently HttpClient as used in https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L32 creates multiple instances of HttpClient which is improper use of the class.

It which needlessly recreates/duplicates the underlying tcp connection pools for each instance of SendGridClient created. More troublesome, it leaves the underlying pools of tcp connections in a wait status for several minutes after each instance of SendGridClient is disposed, using up limited network ports which can often cause issues on cloud platforms such as azure which are easily exhausted.

HttpClient instances should be static, and the underlying threadpool connections should be expired periodically to account for DNS changes for the remote host.

See https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8

### PR DESCRIPTION
**Pull request by akunzai**
# Fixes #670 
# Fixes #897

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Remove HTTP Client Initialization 
- Setup each HTTP request with SendGrid client configuration
- Cleanup constructors
- Prefer options field over Properties

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=839) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=839) it.</sub>

**Comment by aevitas** [comment]
LGTM. This is one of the preconditions to having proper support for ASP.NET Core's DI paradigm, as you'd ideally have a single `HttpClient` instance whose lifetime is managed by the container. 

@thinkingserious Is there a reason this PR has been open for such a long period of time?

**Comment by akunzai** [comment]
solved conflicts for Twilio branding updates

**Comment by thinkingserious** [comment]
Thanks for helping out with a code review once again @aevitas! We appreciate it!

**Comment by thinkingserious** [comment]
Hello @akunzai,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
