### PR TITLE
 Auto Generate Plain Text Content from HTML #536

### PR DESCRIPTION
**Pull request by ganchito55**
I have used the HTMLAgilityPack lib in order to parse and extract the Plain Text Content from a HTML message.
I have not written a test because this lib has been already tested.

#536

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=545) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=545) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=545) it.</sub>

**Comment by thinkingserious** [comment]
Hello @ganchito55,

Instead of introducing a new dependency in the library, would you mind documenting this feature [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md)?

With Best Regards,

elmer

**Comment by ganchito55** [comment]
@thinkingserious I have just send other PR with it.

**Comment by thinkingserious** [comment]
Thank you!

**Pull request closed without merging**
