### PR TITLE
Added PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by veruz**
Closes Issue #595

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=600) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=600) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=600) it.</sub>

**Comment by veruz** [comment]
Sorry if this has already been added/closed. This is my first pull request on someone else's project and I was fiddling around with the fork etc.

**Comment by mbernier** [comment]
Hey, sorry @veruz #596 beat you to this one!

**Comment by veruz** [comment]
No worries, I am just happy I got my head around the fork -> pull request thing with this PR after banging my head about fatal error's trying to push onto a branch on the original project. Good learning experience.

**Pull request closed without merging**
