### PR TITLE
Add Dynamic Template Support

### LINKED ISSUE #716: Add Dynamic Template Support
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#v3-mail-send). 

Now, we need to create helper code and examples for this SDK.

#### Acceptance Criteria

* [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)
* Update the [USE_CASES.md](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [Reference Implementation](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

### PR DESCRIPTION
**Pull request by carl-hartshorn**
# Closes #716

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Add `DynamicTemplateData` property to `Personalization`
- Add helper methods to `SendGridMessage`:
    - `AddDynamicTemplateDataValue`
    - `AddDynamicTemplateDataValues`
- Add new `MailHelper` methods for creating dynamic template emails
    - `CreateSingleDynamicTemplateEmail`
    - `CreateSingleDynamicTemplateEmailToMultipleRecipients`
    - `CreateMultipleDynamicTemplateEmailsToMultipleRecipients`

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=724) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-csharp?pullRequest=724) before we can accept your contribution.<br/><hr/>**Carl Hartshorn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-csharp?pullRequest=724) it.</sub>

**Comment by JaEdmuva** [comment]
@thinkingserious Please, is this coming out any soon?

**Comment by thinkingserious** [comment]
Hi @JaEdmuva,

Yes, we have just released helpers for PHP and now we working to release the Python helpers. C# is next :) 

With Best Regards,

Elmer

**Comment by GlennGeelen** [comment]
Just a little suggest at https://github.com/sendgrid/sendgrid-csharp/pull/724/files#diff-a590903d5d8f3627d1e50f903d70631cR71

If the `DynamicTemplateData` property would be of type `Dictionary<string, object>` it would be possible to also give lists and child objects. So if I have a template that looks like this:
```
<table>
  {{#each list}}
  <tr>
    <td>{{this.title}}</td>
  </tr>
</table>
```
I could do something like:
```c#
var msg = new SendGridMessage
    {
      ...
      Personalizations = new System.Collections.Generic.List<Personalization>()
      {
        new Personalization
        {
          ...
          DynamicTemplateData = new System.Collections.Generic.Dictionary<string, object>()
          {
            { "list", new List<dynamic>()
              {
                new {title = "Title 1"},
                new {title = "Title 2"}
              }
            }
          }
        }
      }
```
I couldn't get the tests to work, else I would have made a PR myself. The scenario above worked for my template and I think it's not that big of a change. What do you think?

**Comment by carl-hartshorn** [comment]
@GlennGeelen yeah that sounds like a good idea to me, especially with the deep object replacement support, I'll look into updating my PR accordingly. Cheers 😄

**Comment by puco** [comment]
Shouldn't `DynamicTemplateData` be just an `object` that should be serialized using a configurable / exposed `JsonSerializerSettings`.

**Comment by carl-hartshorn** [comment]
@puco I like that idea, please see the latest commit. I've gone for simplicity initially and not added `JsonSerializerSettings`. I have added a test though which shows that adding `[JsonProperty("snake_case_property_name")]` for example to the DynamicTemplateData object works.

**Comment by carl-hartshorn** [comment]
Hey @thinkingserious, I was just wondering if your comment here on #716 (https://github.com/sendgrid/sendgrid-csharp/issues/716#issuecomment-416769338) means this PR is redundant?

**Comment by thinkingserious** [comment]
Not at all @carl-hartshorn,

I working from your PR :)

**Comment by carl-hartshorn** [comment]
@thinkingserious ah brilliant 😁 thank you

**Comment by Pieter-1337** [comment]
Hi, can we already use this PR ? When I try to add dynamic template data to a new personalization, it has na parameter for it. I am currently using a workaround which enables me to pass strings, integers etc but I am currently not able to use objects in my templates

**Comment by thinkingserious** [comment]
Hello @carl-hartshorn,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @Pieter-1337,

You can use this PR, but you might want to wait until I publish it on Nuget. The final step before I do that is to QA each of the relevant cases in USE_CASES.md.

With Best Regards,

Elmer

**Comment by CuriousCurmudgeon** [comment]
@thinkingserious Is there an expected turnaround time on that? My team is currently evaluating SendGrid for a project and I'm trying to set expectations around when this will be available.

Also, thanks to you and @carl-hartshorn  for taking care of this!

**Comment by nlatin** [comment]
@thinkingserious yes we are waiting for this realese.. few days?

**Comment by thinkingserious** [comment]
@nlatin, 

Yes, I don't think it should be more than a few working days.

**Comment by ThomasChristmann** [comment]
Did this actually make it into the 9.10. release as the change log suggests? I've updated to 9.10 and am referencing it, but none of the changes are there (no methods on MailHelper, not property on Personalizations, etc)

**Comment by CuriousCurmudgeon** [comment]
@ThomasChristmann It did make it. I'm using it right now. Check out [SendGridMessage#SetTemplateData](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L765) and [SendGridMessage#SetTemplateId](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L1134)

**Pull request merged**
