### PR TITLE
fix spelling error

### PR DESCRIPTION
**Pull request by ajepst**
I was trying my hand at an AppVeyor Build and happened to notice this.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks @ajepst!

Could you please shoot over a [signed CLA](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla) so we can merge it?

Also, thanks for your contributions on the CI thread :)

**Comment by ajepst** [comment]
Sure thing, it's sent!

I still want to have another go at the AppVeyor build before giving up... I
am pretty close, it's now mostly just a matter of getting AppVeyor to deal
properly with that background process kicked off in the pre-build.
(AppVeyor wants to wait for the process to finish some reason even when the
process is set to run in the background) I might try executing the process
with powershell instead of plain command line. Powershell is not my
favorite, but it IS better at some things, this could be one of them...

And hey, if I do give up, I will send along a local-type AppVeyor yml. That
is simpler to get working, and then you will have some basic CI on Windows,
even if it is not the end to end full integration goal.

On Tue, Nov 8, 2016 at 5:32 PM Elmer Thomas notifications-at-github.com
|github| <j4464d63qt@sneakemail.com> wrote:

Thanks @ajepst <https://github.com/ajepst>!

Could you please shoot over a signed CLA
<https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla>
so we can merge it?

Also, thanks for your contributions on the CI thread :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sendgrid/sendgrid-csharp/pull/359#issuecomment-259293164>,
or mute the thread

**Comment by thinkingserious** [comment]
Thank you @ajepst!

I've added this onto our backlog for review.

**Comment by thinkingserious** [comment]
Hi @ajepst,

This came up on our backlog to merge. Could you please update the conflicts? Thanks!

**Comment by ajepst** [comment]
Looks like this no longer applies.

**Pull request closed without merging**
