### PR TITLE
.NET 4.5.X, 4.6.X and CORE Support

### PR DESCRIPTION
**Pull request by thinkingserious**

### CODE REVIEW

**Comment by thinkingserious** [comment]
I'm going to merge this into the v9beta branch and move to the Mail Helper refactor and revisit Travis later. Currently, the tests are working locally.

**Comment by StephenRedd** [comment]
Any chance we can get the beta netstandard packages published to nuget soon?

**Comment by thinkingserious** [comment]
@StephenRedd,

I can not promise a particular date, but this is a top priority for us and I hope to have a beta pushed to Nuget very soon. In the mean time, @Jericho's https://github.com/Jericho/StrongGrid is a solid alternative.

**Comment by StephenRedd** [comment]
Yeah, no worries. I built the source locally and made my own packages for now.

**Pull request merged**
